unit CNT416;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Grids, Wwdbigrd, Wwdbgrid, StdCtrls, ExtCtrls, Buttons, Mask, wwdbedit,
  wwdblook, Wwdbdlg;

type
  TForm1 = class(TForm)
    Panel1: TPanel;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    wwDBLookupComboDlg1: TwwDBLookupComboDlg;
    wwDBLookupCombo1: TwwDBLookupCombo;
    wwDBLookupComboDlg2: TwwDBLookupComboDlg;
    Label4: TLabel;
    wwDBEdit1: TwwDBEdit;
    wwDBEdit2: TwwDBEdit;
    wwDBLookupCombo2: TwwDBLookupCombo;
    Label5: TLabel;
    wwDBLookupComboDlg3: TwwDBLookupComboDlg;
    wwDBEdit3: TwwDBEdit;
    wwDBLookupCombo3: TwwDBLookupCombo;
    Label6: TLabel;
    wwDBEdit4: TwwDBEdit;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    Bevel1: TBevel;
    StaticText1: TStaticText;
    StaticText2: TStaticText;
    StaticText3: TStaticText;
    StaticText4: TStaticText;
    StaticText5: TStaticText;
    Bevel2: TBevel;
    Bevel3: TBevel;
    Bevel4: TBevel;
    Bevel5: TBevel;
    Bevel6: TBevel;
    Bevel7: TBevel;
    wwDBEdit19: TwwDBEdit;
    wwDBEdit20: TwwDBEdit;
    wwDBEdit21: TwwDBEdit;
    wwDBEdit22: TwwDBEdit;
    wwDBEdit23: TwwDBEdit;
    wwDBEdit24: TwwDBEdit;
    wwDBEdit25: TwwDBEdit;
    wwDBEdit26: TwwDBEdit;
    wwDBEdit27: TwwDBEdit;
    wwDBEdit28: TwwDBEdit;
    wwDBEdit29: TwwDBEdit;
    wwDBEdit30: TwwDBEdit;
    wwDBEdit31: TwwDBEdit;
    wwDBEdit32: TwwDBEdit;
    wwDBEdit33: TwwDBEdit;
    wwDBEdit34: TwwDBEdit;
    wwDBEdit35: TwwDBEdit;
    wwDBEdit36: TwwDBEdit;
    wwDBEdit37: TwwDBEdit;
    wwDBEdit38: TwwDBEdit;
    wwDBEdit39: TwwDBEdit;
    wwDBEdit40: TwwDBEdit;
    wwDBEdit41: TwwDBEdit;
    wwDBEdit42: TwwDBEdit;
    wwDBEdit43: TwwDBEdit;
    wwDBEdit44: TwwDBEdit;
    wwDBEdit45: TwwDBEdit;
    wwDBEdit46: TwwDBEdit;
    wwDBEdit47: TwwDBEdit;
    wwDBEdit48: TwwDBEdit;
    wwDBEdit49: TwwDBEdit;
    wwDBEdit50: TwwDBEdit;
    wwDBEdit51: TwwDBEdit;
    wwDBEdit52: TwwDBEdit;
    wwDBEdit53: TwwDBEdit;
    wwDBEdit54: TwwDBEdit;
    wwDBEdit55: TwwDBEdit;
    wwDBEdit56: TwwDBEdit;
    wwDBEdit57: TwwDBEdit;
    wwDBEdit58: TwwDBEdit;
    wwDBEdit59: TwwDBEdit;
    wwDBEdit60: TwwDBEdit;
    wwDBEdit61: TwwDBEdit;
    wwDBEdit62: TwwDBEdit;
    wwDBEdit63: TwwDBEdit;
    wwDBEdit64: TwwDBEdit;
    wwDBEdit65: TwwDBEdit;
    wwDBEdit66: TwwDBEdit;
    wwDBEdit67: TwwDBEdit;
    wwDBEdit68: TwwDBEdit;
    wwDBEdit69: TwwDBEdit;
    wwDBEdit70: TwwDBEdit;
    wwDBEdit71: TwwDBEdit;
    wwDBEdit72: TwwDBEdit;
    wwDBEdit73: TwwDBEdit;
    wwDBEdit74: TwwDBEdit;
    wwDBEdit75: TwwDBEdit;
    wwDBEdit76: TwwDBEdit;
    wwDBEdit77: TwwDBEdit;
    wwDBEdit78: TwwDBEdit;
    wwDBEdit5: TwwDBEdit;
    wwDBEdit6: TwwDBEdit;
    wwDBEdit7: TwwDBEdit;
    wwDBEdit8: TwwDBEdit;
    wwDBEdit9: TwwDBEdit;
    wwDBEdit10: TwwDBEdit;
    wwDBEdit11: TwwDBEdit;
    wwDBEdit12: TwwDBEdit;
    wwDBEdit13: TwwDBEdit;
    wwDBEdit14: TwwDBEdit;
    wwDBEdit15: TwwDBEdit;
    wwDBEdit16: TwwDBEdit;
    wwDBEdit17: TwwDBEdit;
    wwDBEdit18: TwwDBEdit;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

uses CNTDM;
{$R *.DFM}

end.
